### ISSUE TITLE
How i can use this ranker after i installed it?

### ISSUE THREAD

**Issue by eivenhoe** [Palaxx/non-fungible-ranker#1]
From the readme i dont know how to use it, where i can define the parameters?
And how i can run it?
Kind regards

**Comment by Palaxx** [comment]
Hello, 

first of all thanks for you issue, you are right the readme is probably incomplete. 

The package now accept only the _filesystem_ source which expect to receive in the **source.path** options the path of a folder with the metadata json for each nft of collections. 

See [metadata-standards](https://docs.opensea.io/docs/metadata-standards). 

Filesystem source is useful tipically when you have generated a collection by yourself and you have all the metadata in your pc.

In the next days, I should work on a new source which fetch metadata directly from the blockchain contract. 

By the way assuming you have the metadata files into **./metadata/** folder, and a single metadata in something like this
```json
{
  "description": "First element of my nft collection",
  "name": "NFT #1",
  "attributes": [
    {
      "trait_type": "Base",
      "value": "Starfish"
    },
    {
      "trait_type": "Eyes",
      "value": "Big"
    },
    {
      "trait_type": "Mouth",
      "value": "Surprised"
    }
  ]
}
```
you should be able to rank the collection using the following snippet
```javascript
const options = {
    source: {
        type: 'filesystem',
        path: './metadata/',
    },
    collection: {
        attributes: ['Base','Eyes','Mouth'],
        supply: 10000
    },
    ranker: {
        type: 'rarityScore'
    }
}
```

The **collection.attributes** field is used to include/exclude trait from rank contribution. 
If you want to rank the collection only using _Mouth_ and _Eyes_ trait the previous snipped should not includes **Base** in the attribute field.

**Comment by eivenhoe** [comment]
I have all the json Metadata locally, this is exactly what i need. but for me its not clear after i installed the NON-Fungible-Ranker (npm install non-fungible-ranker) how can i run the rarity ranker.
First where i have to put in the snippet? Normally there is like a config.js i put in all information.
Where i have to put in the snippet and how i can run the snippet?
Do i need to make a new file or run the snippet in Terminal?
Do i have to cusomtize the test js files?
I am no expert at visual.

Kind regards

**Comment by Palaxx** [comment]
Ok understood. 

You need to set up a new node js project, create an index.js file and copy paste the snippet.

Assuming you are on unix system

### Initialize the project
```shell
mkdir my-node-project
cd my-node-project
npm init -y
npm install non-fungible-ranker

# create a new index.js file and paste the snippet

node index.js
```

### Create the node file
```javascript
// Create a new file called index.js with this content
const NFR = require('non-fungible-ranker')

async function run () {
    const options = {
        source: {
            type: 'filesystem',
            path: './inputs/json',
        },
        collection: {
            attributes: ['Background','Skin', 'Jowls', 'Mouth', 'Eyes', 'Clothes', 'Headwear'],
            supply: 10000
        },
        ranker: {
            type: 'rarityScore'
        }
    }
    const ranker = NFR(options)

    const stats = await ranker.rankCollection()
    console.log(stats)
}

run()
```

### Execute the file
```shell
node index.js
```

Running the index file should print to console all the scores, probably you can make the result less ephemeral writing it to a file

```javascript
async function run () {
 // ...
 const ranker = NFR(options)
 const stats = await ranker.rankCollection()
 const data = JSON.stringify(
    stats,
    null,
    4
  );

  await fs.writeFile(`./outputFolder/scores.json`, data, "utf8");
 // ...
}
```

Let me know if it works for you

**Comment by eivenhoe** [comment]
Thanks for explaining it worked with a little bit tweaking for the file writing:)

    const data = JSON.stringify(
        stats,
        null,
        4
    );
    const fs = require("fs"); <-- this was missing
    await fs.writeFileSync('.\summary.json', data, 'utf8'); <-- i used writeFileSync otherwise writeFile want a Callback Parameter

}

To show more than 100 items in console log
    const stats = await ranker.rankCollection()

    const util = require('util')
    console.log(util.inspect(stats, { maxArrayLength: null }))
    //console.log(stats)


I have some optimizing suggestions for the program:
It would also be nice if the scores are sorted
It would be nice if a column rank was there (example id: 432, score: 151, rank: 5)
How can i export this data to a csv to sort it manually?

Kind regards

**Comment by Palaxx** [comment]
Hello!

Thanks for the suggestions, what is the meaning of rank field? Is the current position in the "scoreboard"?

In the first versions I decided to left sorts and file persistance outside the package, I' m trying to make a small package which do only few, well defined, things.
But i don't exclude that sorting could be done directly by the package in the next versions

By the way sorting and rank field should be easily accomplished with something like this:
```javascript
const stats = await ranker.rankCollection()
const orderedStats = stats
    .sort((el1, el2) => el1.score - el2.score)
    .map(({score, id}, position) => ({
            id,
            score,
            rank: position + 1
        })
    )
```
while write a file csv can be done using an external package as explained in this guide [write & read csv](https://stackabuse.com/reading-and-writing-csv-files-with-node-js/)
